repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
          - '--args=--only=terraform_unused_required_providers'
    - id: terraform_validate
      args:
          - --hook-config=--retry-once-with-cleanup=true
    - id: terraform_docs
      args:
      - --hook-config=--create-file-if-not-exist=true
      - --hook-config=--use-standard-markers=true
      - --hook-config=--path-to-file=README.md
      - --args=--output-mode=inject

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
